import {
  Component,
  ChangeDetectionStrategy,
  input,
  output,
  signal,
  computed,
  effect,
  inject,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormControl } from '@angular/forms';
import { MonacoEditorModule } from 'ngx-monaco-editor-v2';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatTooltipModule } from '@angular/material/tooltip';
import { NotificationService } from '../../services/notification.service';
import { ThemeService } from '../../services/theme.service';
import { WINDOW } from '../../tokens';

/**
 * Component to view code files generated by WASM.
 * Implements a tabbed interface and a read-only Monaco Editor.
 */
@Component({
  selector: 'app-code-viewer',
  /** imports */
  imports: [
    CommonModule,
    ReactiveFormsModule,
    MonacoEditorModule,
    MatButtonModule,
    MatIconModule,
    MatTooltipModule,
  ],
  /** template */
  template: `
    <div class="code-viewer-container">
      <div
        class="toolbar"
        role="toolbar"
        aria-label="Code Viewer Actions"
        i18n-aria-label="@@codeViewerActionsAria"
      >
        <div class="tabs-container" role="tablist">
          @for (tab of openTabs(); track tab) {
            <div
              class="tab"
              role="tab"
              tabindex="0"
              [class.active]="tab === activeFilePath()"
              [attr.aria-selected]="tab === activeFilePath()"
              (click)="selectTab(tab)"
              (keydown.enter)="selectTab(tab, $event)"
              (keydown.space)="selectTab(tab, $event)"
            >
              <span [title]="tab">{{ getFilename(tab) }}</span>
              <div
                class="tab-close"
                role="button"
                tabindex="0"
                aria-label="Close Tab"
                i18n-aria-label="@@closeTabAria"
                (click)="closeTab(tab, $event)"
                (keydown.enter)="closeTab(tab, $event)"
                (keydown.space)="closeTab(tab, $event)"
              >
                <mat-icon>close</mat-icon>
              </div>
            </div>
          }
        </div>

        <div class="actions">
          <button
            mat-icon-button
            (click)="copyToClipboard()"
            [disabled]="!activeFilePath()"
            matTooltip="Copy File Content"
            i18n-matTooltip
            aria-label="Copy to Clipboard"
            i18n-aria-label="@@copyToClipboardAria"
          >
            <mat-icon>content_copy</mat-icon>
          </button>

          <button
            mat-icon-button
            (click)="downloadFile()"
            [disabled]="!activeFilePath()"
            matTooltip="Download File"
            i18n-matTooltip="@@downloadFileTooltip"
            aria-label="Download File"
            i18n-aria-label="@@downloadFileAria"
          >
            <mat-icon>download</mat-icon>
          </button>
        </div>
      </div>

      <div class="editor-wrapper">
        @if (activeFilePath() && fileContent() !== null) {
          <!-- We use formControl for read-only binding via Angular's standard form integration -->
          <ngx-monaco-editor
            [options]="editorOptions()"
            [formControl]="contentControl"
          ></ngx-monaco-editor>
        } @else {
          <div class="empty-state">
            <mat-icon>code_off</mat-icon>
            <p i18n="@@noFileSelected">No file selected</p>
            <p style="font-size: 0.8rem; margin-top: 0.5rem;" i18n="@@selectFilePrompt">
              Select a file from the Explorer to view its contents.
            </p>
          </div>
        }
      </div>
    </div>
  `,
  /** styleUrl */
  styleUrl: './code-viewer.component.css',
  /** changeDetection */
  changeDetection: ChangeDetectionStrategy.OnPush,
})
/** CodeViewerComponent */
export class CodeViewerComponent {
  /** The path of the currently active file to view. */
  activeFilePath = input<string | null>(null);

  /** The content of the currently active file. */
  fileContent = input<string | null>(null);

  /** Emitted when the user selects a tab. */
  fileSelected = output<string>();

  /** Internal state keeping track of which tabs are currently open. */
  openTabs = signal<string[]>([]);

  /** Form control for the read-only Monaco editor */
  contentControl = new FormControl('');

  /** Notification service for user feedback. */
  private notificationService = inject(NotificationService);
  /** Theme service for editor configuration. */
  private themeService = inject(ThemeService);
  /** Window token. */
  private window = inject(WINDOW);

  /** Computed options for the Monaco editor. */
  editorOptions = computed(() => ({
    /** theme */
    theme: this.themeService.isDarkTheme() ? 'vs-dark' : 'vs',
    /** language */
    language: this.determineLanguage(this.activeFilePath() || ''),
    /** readOnly */
    readOnly: true,
    /** automaticLayout */
    automaticLayout: true,
    /** minimap */
    minimap: { enabled: false },
    /** scrollBeyondLastLine */
    scrollBeyondLastLine: false,
    /** wordWrap */
    wordWrap: 'on',
    /** renderLineHighlight */
    renderLineHighlight: 'none',
  }));

  /**
   * Initializes the component, setting up effects to open tabs automatically.
   */
  constructor() {
    // Automatically open a tab if a new active file path is provided externally
    effect(
      () => {
        const activePath = this.activeFilePath();
        if (activePath) {
          this.ensureTabIsOpen(activePath);
        }
      },
      { allowSignalWrites: true },
    );

    // Sync file content to the form control
    effect(() => {
      const content = this.fileContent() || '';
      if (this.contentControl.value !== content) {
        this.contentControl.setValue(content, { emitEvent: false });
      }
    });
  }

  /**
   * Ensures a file path is in the openTabs array.
   */
  private ensureTabIsOpen(path: string): void {
    if (!this.openTabs().includes(path)) {
      this.openTabs.update((tabs) => [...tabs, path]);
    }
  }

  /**
   * Selects a tab to view.
   * @param path The file path to select.
   * @param event Optional DOM event, used to prevent default behavior on key presses.
   */
  selectTab(path: string, event?: Event): void {
    if (event) {
      event.preventDefault();
    }
    if (path !== this.activeFilePath()) {
      this.fileSelected.emit(path);
    }
  }

  /**
   * Closes a tab. If the active tab is closed, automatically selects another open tab or null.
   * @param path The file path to close.
   * @param event The DOM event to stop propagation.
   */
  closeTab(path: string, event: Event): void {
    event.preventDefault();
    event.stopPropagation();

    const tabs = this.openTabs();
    const newTabs = tabs.filter((t) => t !== path);
    this.openTabs.set(newTabs);

    // If we closed the currently active tab, we need to pick a new one
    if (path === this.activeFilePath()) {
      if (newTabs.length > 0) {
        // Pick the last tab available
        this.fileSelected.emit(newTabs[newTabs.length - 1]);
      } else {
        // Nothing left to select
        this.fileSelected.emit('');
      }
    }
  }

  /**
   * Copies the current file content to the clipboard.
   */
  async copyToClipboard(): Promise<void> {
    const content = this.fileContent();
    if (!content) return;

    try {
      await navigator.clipboard.writeText(content);
      this.notificationService.success('Copied to clipboard.');
    } catch {
      this.notificationService.error('Failed to copy to clipboard.');
    }
  }

  /**
   * Triggers a download of the current file content.
   */
  downloadFile(): void {
    const content = this.fileContent();
    const path = this.activeFilePath();

    if (!content) return;
    // We already check path indirectly because if activeFilePath is null, button is disabled.
    // But for type safety/coverage:
    if (!path) return;

    const filename = this.getFilename(path);
    const blob = new Blob([content], { type: 'text/plain' });
    if (!this.window) return;
    const windowWithUrl = this.window as unknown as { URL: typeof URL };
    const url = windowWithUrl.URL.createObjectURL(blob);

    const a = this.window.document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();

    windowWithUrl.URL.revokeObjectURL(url);
    this.notificationService.success(`Downloading ${filename}...`);
  }

  /**
   * Extracts just the filename from a full path.
   */
  getFilename(path: string): string {
    return path.split('/').pop() || path;
  }

  /**
   * Determines the appropriate Monaco language string based on file extension.
   * Covers the 13 required languages.
   */
  determineLanguage(path: string): string {
    const ext = path.split('.').pop()?.toLowerCase();

    switch (ext) {
      case 'ts':
      case 'tsx':
        return 'typescript';
      case 'js':
      case 'jsx':
        return 'javascript';
      case 'json':
        return 'json';
      case 'yaml':
      case 'yml':
        return 'yaml';
      case 'md':
        return 'markdown';
      case 'html':
        return 'html';
      case 'css':
        return 'css';
      case 'scss':
        return 'scss';
      case 'rs':
        return 'rust';
      case 'go':
        return 'go';
      case 'py':
        return 'python';
      case 'rb':
        return 'ruby';
      case 'java':
        return 'java';
      case 'kt':
      case 'kts':
        return 'kotlin';
      case 'swift':
        return 'swift';
      case 'cs':
        return 'csharp';
      case 'cpp':
      case 'cc':
      case 'cxx':
      case 'h':
      case 'hpp':
        return 'cpp';
      case 'c':
        return 'c';
      case 'php':
        return 'php';
      case 'sh':
      case 'bash':
        return 'shell';
      default:
        return 'plaintext';
    }
  }
}
