import { GeneratedFile } from '../services/wasm-worker.service';

import { Target, LanguageOptions } from '../models/types';

/**
 * Defines the orientation of the split pane.
 * 'openapi-left' means OpenAPI editor is on the left, Code on the right.
 * 'openapi-right' means OpenAPI editor is on the right, Code on the left.
 */
export type LayoutOrientation = 'openapi-left' | 'openapi-right';

/**
 * State slice for general workspace settings.
 */
export interface WorkspaceState {
  /** The current orientation of the split pane layout. */
  orientation: LayoutOrientation;
  /** Whether an execution (WASM generation) is currently running. */
  isExecuting: boolean;
  /** The ID of the currently selected programming language. */
  selectedLanguageId: string;
  /** The target generation type. */
  target: Target;
  /** Additional generation options mapped by language ID. */
  languageOptions: Record<string, LanguageOptions>;
}

/**
 * State slice for the generated file tree.
 */
export interface FileTreeState {
  /** The list of files generated by the WASM execution. */
  files: GeneratedFile[];
  /** The path of the currently selected/active file in the viewer. */
  activeFilePath: string | null;
}

/**
 * State slice for the OpenAPI specification editor.
 */
export interface OpenApiState {
  /** The selected input format. */
  inputFormat: import('../models/types').InputFormat;
  /** The current content of the OpenAPI specification. */
  specContent: string;
  /** Any validation errors present in the current specification. */
  validationErrors: string[];
}

/**
 * Represents the global application state.
 */
export interface AppState {
  /** The workspace state slice. */
  workspace: WorkspaceState;
  /** The file tree state slice. */
  fileTree: FileTreeState;
  /** The OpenAPI state slice. */
  openApi: OpenApiState;
}
