#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running Formatters..."
npm run format
npm run format:check

echo "Running Linters..."
npm run lint

echo "Running Build..."
npm run build

echo "Running Tests with Coverage..."
npm run test:coverage

echo "Running E2E Tests..."
npm run e2e

echo "Updating Coverage Shields..."
node scripts/update-shields.mjs

git add README.md
